config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants
  resources :movies, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/director.rb
class Director < ApplicationRecord
    has_many :movies

end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :director

  include PgSearch::Model
  # multisearchable against: [:title, :synopsis],
  # pg_search_scope :search_by_title_and_synopsis,
  pg_search_scope :global_search,
    against: [ :title, :synopsis ],
    associated_against: {
      director: [ :first_name, :last_name]
    },
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    geocoded_by :address
    after_validation :geocode, if: :will_save_change_to_address?

    belongs_to :user
    has_one_attached :photo

    validates :name, presence: true
    validates :address, presence: true
end

app/models/tv_show.rb
class TvShow < ApplicationRecord
    include PgSearch::Model
    multisearchable against: [:title, :synopsis]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :restaurants, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?
    include Pundit::Authorization

     # Pundit: white-list approach
    after_action :verify_authorized, except: :index, unless: :skip_pundit?
    # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

    def configure_permitted_parameters
        # For additional fields in app/views/devise/registrations/new.html.erb
        devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    
        # For additional in app/views/devise/registrations/edit.html.erb
        devise_parameter_sanitizer.permit(:account_update, keys: [:nickname])
    end

    def skip_pundit?
        devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
    end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

    def index
        @movies = Movie.all
        if params[:query].present?
            @movies = Movie.global_search(params[:query])
          else
            @movies = Movie.all
        end
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
    before_action :set_restaurant, only: [:show, :edit, :update, :destroy]


    def index
        # @restaurants = Restaurant.all
        @restaurants = policy_scope(Restaurant)

        @markers = @restaurants.geocoded.map do |restaurant|
            {
              lat: restaurant.latitude,
              lng: restaurant.longitude,
              info_window: render_to_string(partial: "info_window", locals: { restaurant: restaurant })
            }
        end
    end

    def show
        
    end

    def new
        @restaurant = Restaurant.new
        authorize @restaurant
    end

    def create
        @restaurant = Restaurant.new(restaurant_params)
        @restaurant.user = current_user
        authorize @restaurant
        if @restaurant.save
            redirect_to restaurants_path
        else
            render :new
        end
    end

    def edit
        
    end

    def update
        if @restaurant.update(restaurant_params)
            redirect_to restaurants_path
        else
            render :edit
        end
    end

    def destroy
        @restaurant.destroy
        redirect_to restaurants_path
    end

    private

    def set_restaurant
        @restaurant = Restaurant.find(params[:id])
        authorize @restaurant
    end

    def restaurant_params
        params.require(:restaurant).permit(:name, :address, :photo)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApis</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/movies/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-sm-8">
        <%= form_tag movies_path, method: :get, class: "d-flex" do %>
            <%= text_field_tag :query,
                params[:query],
                class: "form-control",
                placeholder: "Find a movie"
        %>
        <%= submit_tag "Search", class: "btn btn-primary" %>
    <% end %>
      <div id="movies">
        <% @movies.each do |movie| %>
          <h4><%= movie.title %></h4>
          <p><%= movie.synopsis %></p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<%= cl_image_tag("hztyzrpsdhkwkunmw840",
      width: 400, height: 300, crop: :fill) %>

<!-- for face detection -->
<%= cl_image_tag("ev7iakw6cge381jef4vf",
      width: 150, height: 150, crop: :thumb, gravity: :face) %>


<p> <%= link_to 'Check restaurants', restaurants_path %></p>
<p> <%= link_to 'Check movies', movies_path %></p>

app/views/restaurants/_form.html.erb
<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address, input_html: { data: { geocoder_target: "address" }, class: "d-none"},
  wrapper_html: { data: { controller: "geocoder", geocoder_api_key_value: ENV['MAPBOX_API_KEY'] } } %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/restaurants/_info_window.html.erb
<h2><%= restaurant.name %></h2>
<p><%= restaurant.address %></p>
<%= cl_image_tag restaurant.photo.key, height: 60, width: 80%>

app/views/restaurants/edit.html.erb
<%= render "form", restaurant: @restaurant %>

app/views/restaurants/index.html.erb
<h1>All the restaurants</h1>

<% @restaurants.each do |restaurant| %>
<p> <%= restaurant.name %> at the address <%= restaurant.address %> 
<%= cl_image_tag restaurant.photo.key, height: 100, width: 200 %>

<%= link_to 'Edit', edit_restaurant_path(restaurant) if policy(restaurant).edit? %>


<% if policy(restaurant).destroy? %>
  <%= link_to "Delete #{restaurant.name}",
              restaurant_path(restaurant),
              method: :delete,
              data: { confirm: "Are you sure?" } %>
<% end %>


</p>

<% end %>


<%= link_to 'Create a new restaurant', new_restaurant_path %>
<link href='https://api.tiles.mapbox.com/mapbox-gl-js/v1.8.0/mapbox-gl.css' rel='stylesheet' />
<div style="width: 100%; height: 600px;"
  data-controller="mapbox"
  data-mapbox-markers-value="<%= @markers.to_json %>"
  data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

app/views/restaurants/new.html.erb
<%= render "form", restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>

<p><%= @restaurant.address %></p>

<% if policy(@restaurant).edit? %>
<%= link_to 'Edit', edit_restaurant_path(@restaurant) %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active nav-link">
             <%= current_user.nickname  %> 
          </li>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>